/**
 * UMS — Unified Messaging System types
 *
 * ELLIE-293: Core type definitions for the normalized message store.
 * UMS is a dumb pipe: these types describe what arrives, not what to do with it.
 */

/** Known providers. Extensible — new providers just add a string. */
export type Provider =
  | "telegram"
  | "gmail"
  | "gchat"
  | "calendar"
  | "github"
  | "outlook"
  | "slack"
  | "discord"
  | "voice"
  | (string & {});

/** Content type of the normalized message. */
export type ContentType =
  | "text"
  | "voice"
  | "image"
  | "event"
  | "task"
  | "notification"
  | (string & {});

/** Sender identity — shape varies by provider, all fields optional. */
export interface Sender {
  name?: string;
  email?: string;
  username?: string;
  id?: string;
}

/**
 * The core UMS record — one row per inbound message/event/notification.
 *
 * Maps 1:1 to the `unified_messages` table.
 */
export interface UnifiedMessage {
  id: string;
  provider: Provider;
  provider_id: string;
  channel: string | null;
  sender: Sender | null;
  content: string | null;
  content_type: ContentType;
  raw: Record<string, unknown>;
  received_at: string;
  provider_timestamp: string | null;
  metadata: Record<string, unknown>;
}

/**
 * Input for creating a new UnifiedMessage.
 * `id` and `received_at` are auto-generated by the database.
 */
export interface UnifiedMessageInsert {
  provider: Provider;
  provider_id: string;
  channel?: string | null;
  sender?: Sender | null;
  content?: string | null;
  content_type: ContentType;
  raw: Record<string, unknown>;
  provider_timestamp?: string | null;
  metadata?: Record<string, unknown>;
}

/** Filters for querying unified messages (pull path). */
export interface MessageQueryFilters {
  provider?: Provider;
  content_type?: ContentType;
  channel?: string;
  since?: string;       // ISO 8601 timestamp — messages after this time
  before?: string;      // ISO 8601 timestamp — messages before this time
  limit?: number;       // max results (default 50, max 500)
}
