export type {
  MountainSource,
  SourceStatus,
  HarvestJob,
  HarvestResult,
  HarvestItem,
  HarvestError,
} from "./types.ts";

export { MountainOrchestrator } from "./orchestrator.ts";

export type { MountainRecord, MountainRecordStatus, InsertMountainRecord } from "./records.ts";
export {
  insertRecord,
  upsertRecord,
  getRecord,
  getRecordByExternalId,
  listRecords,
  updateRecordStatus,
  countRecords,
} from "./records.ts";

export { MCPConnectorSource, type MCPToolCaller, type MCPConnectorConfig } from "./mcp-connector.ts";
export { GoogleWorkspaceMountainSource } from "./connectors/google-workspace.ts";
export { GitHubMountainSource } from "./connectors/github.ts";
export { PlaneMountainSource } from "./connectors/plane.ts";

export {
  MessageIngestionSource,
  ingestMessage,
  normalizeMessage,
  detectRecordType,
  resolveSender,
  setIngestionEnabled,
  isIngestionEnabled,
  enableChannel,
  disableChannel,
  isChannelEnabled,
  getEnabledChannels,
  type IncomingMessage,
  type MessageChannel,
  type MessageRecordType,
  type NormalizedMessagePayload,
  type MessageFetcher,
  type MessageFetchOptions,
} from "./message-ingestion.ts";

export {
  RiverSink,
  mapRecordToDocument,
  buildDocumentPath,
  buildDocumentContent,
  buildFrontmatter,
  sanitizePathSegment,
  _makeMockRecord,
  type RawDocument,
  type RiverSinkResult,
  type RiverSinkConfig,
} from "./river-sink.ts";

export {
  ClaudeEntityExtractor,
  IdentityResolver,
  ExtractionPipeline,
  buildExtractionPrompt,
  parseExtractionResponse,
  validateEntity,
  getContentFromRecord,
  buildEntityDocument,
  normalizeName,
  _makeMockRecordForExtraction,
  _makeMockClaudeCallFn,
  _makeMockClaudeCallFnError,
  type EntityExtractor,
  type EntityType,
  type ExtractedEntity,
  type PersonEntity,
  type TopicEntity,
  type ActionItemEntity,
  type DecisionEntity,
  type PersonIdentifier,
  type ExtractionResult,
  type ExtractionConfig,
  type IdentityProfile,
  type ClaudeCallFn,
} from "./entity-extraction.ts";

export {
  ContactSeedPipeline,
  scoreContactMatch,
  fuzzyNameMatch,
  normalizeName as normalizeContactName,
  normalizePhone,
  getFieldValues,
  appleContactToRecord,
  googleContactToRecord,
  discordMemberToRecord,
  linkedInConnectionToRecord,
  telegramUserToRecord,
  parseLinkedInCsv,
  parseCsvLine,
  buildContactPayload,
  resolveSenderIdentity,
  _makeMockContact,
  _makeMockWriter,
  _makeMockSourceAdapter,
  type ContactRecord,
  type ChannelIdentifier,
  type SeedResult,
  type MatchRule,
  type MatchField,
  type ContactIdentityPayload,
  type ContactRecordWriter,
  type ContactSourceAdapter,
  type AppleContactInput,
  type GoogleContactInput,
  type DiscordMemberInput,
  type LinkedInConnectionInput,
  type TelegramUserInput,
} from "./contact-seed.ts";

export {
  runBackfill,
  normalizeSupabaseMessage,
  detectBackfillRecordType,
  _makeMockSupabaseMessage,
  _makeMockFetcher,
  _makeMockWriter as _makeMockBackfillWriter,
  type SupabaseMessage,
  type BackfillOptions,
  type BackfillProgress,
  type BackfillResult,
  type BackfillChannel,
  type NormalizedBackfillRecord,
  type SupabaseFetcher,
  type MountainWriter,
} from "./message-backfill.ts";

export {
  InteractionScoringPipeline,
  computeRecencyScore,
  computeFrequencyScore,
  computeDirectionScore,
  computeOverallScore,
  buildChannelStats,
  simpleTopicExtractor,
  buildRelationshipDocument,
  _makeMockInteractionMessage,
  _makeMockScoringContact,
  _makeMockMessageFetcher,
  _makeMockContactLookup,
  type InteractionMessage,
  type ScoringContact,
  type RelationshipType,
  type ChannelStats,
  type InteractionScore,
  type ScoringWeights,
  type ScoringConfig,
  type RelationshipQuery,
  type RelationshipQueryResult,
  type RelationshipDocument,
  type InteractionMessageFetcher,
  type ContactLookup,
  type TopicExtractor,
} from "./interaction-scoring.ts";

export {
  GoogleContactsSyncPipeline,
  mapRawToInput,
  parseContactsListResponse,
  _makeMockGoogleContactRaw,
  _makeMockGoogleContactsFetcher,
  _makeMockSyncStateStore,
  _makeMockContactWriter,
  type GoogleContactRaw,
  type GoogleContactsPage,
  type SyncState,
  type GoogleContactsSyncConfig,
  type SyncResult,
  type SyncError,
  type SyncProgress,
  type SyncProgressCallback,
  type GoogleContactsFetcher,
  type SyncStateStore,
} from "./google-contacts-sync.ts";

export {
  EmailBatchProcessor,
  InMemoryBatchStateStore,
  parseSender,
  isNewsletter,
  isUrgentEmail,
  processEmailRecord,
  groupBySender,
  collapseThreads,
  proposeAction,
  formatBatchReport,
  buildGtdItem,
  _makeMockEmailRecord,
  _makeMockFetcher as _makeMockEmailFetcher,
  _makeMockStateStore,
  NEWSLETTER_SENDER_PATTERNS,
  NEWSLETTER_SUBJECT_PATTERNS,
  URGENT_KEYWORDS,
  type MountainEmailRecord,
  type ProcessedEmail,
  type EmailGroup,
  type BatchResult,
  type GtdInboxItem,
  type BatchProcessorDeps,
  type EmailRecordFetcher,
  type BatchStateStore,
} from "./email-batch-processor.ts";
