/**
 * Workflow Message Type Generator — ELLIE-833
 *
 * Reads archetype produces/consumes definitions and generates
 * type-safe message schemas. Validates that agents only send
 * message types declared in their produces list.
 */

import { type ArchetypeSchema, type MessageType, MESSAGE_TYPES } from "./archetype-schema.ts";

// ── Types ────────────────────────────────────────────────────────

/** Message contract for an agent: what it can send and receive. */
export interface AgentMessageContract {
  agent: string;
  species: string;
  produces: MessageType[];
  consumes: MessageType[];
}

/** A workflow message between agents. */
export interface WorkflowMessage {
  id: string;
  workflow_id: string;
  sender: string;
  receiver: string;
  type: MessageType;
  payload: Record<string, unknown>;
  timestamp: string;
}

/** Result of validating a message against contracts. */
export interface MessageValidation {
  valid: boolean;
  error?: string;
}

// ── Contract extraction ──────────────────────────────────────────

/**
 * Extract message contract from a parsed archetype.
 * Returns the agent name (from species or hint) and its produces/consumes lists.
 */
export function extractContract(schema: ArchetypeSchema, agentName: string): AgentMessageContract {
  return {
    agent: agentName,
    species: schema.frontmatter.species,
    produces: schema.frontmatter.produces ?? [],
    consumes: schema.frontmatter.consumes ?? [],
  };
}

/**
 * Build a complete contract registry from all loaded archetypes.
 * Map key is the agent name (e.g. "dev", "critic").
 */
export function buildContractRegistry(
  archetypes: Map<string, ArchetypeSchema>,
): Map<string, AgentMessageContract> {
  const registry = new Map<string, AgentMessageContract>();
  for (const [name, schema] of archetypes) {
    registry.set(name, extractContract(schema, name));
  }
  return registry;
}

// ── Validation ───────────────────────────────────────────────────

/**
 * Validate that a sender is allowed to produce a given message type.
 */
export function validateSend(
  registry: Map<string, AgentMessageContract>,
  sender: string,
  messageType: MessageType,
): MessageValidation {
  const contract = registry.get(sender);
  if (!contract) {
    return { valid: false, error: `Unknown agent "${sender}" — not in contract registry` };
  }
  if (!contract.produces.includes(messageType)) {
    return {
      valid: false,
      error: `Agent "${sender}" cannot produce "${messageType}". Allowed: ${contract.produces.join(", ") || "none"}`,
    };
  }
  return { valid: true };
}

/**
 * Validate that a receiver can consume a given message type.
 */
export function validateReceive(
  registry: Map<string, AgentMessageContract>,
  receiver: string,
  messageType: MessageType,
): MessageValidation {
  const contract = registry.get(receiver);
  if (!contract) {
    return { valid: false, error: `Unknown agent "${receiver}" — not in contract registry` };
  }
  if (!contract.consumes.includes(messageType)) {
    return {
      valid: false,
      error: `Agent "${receiver}" cannot consume "${messageType}". Accepted: ${contract.consumes.join(", ") || "none"}`,
    };
  }
  return { valid: true };
}

/**
 * Validate a full message: sender can produce it AND receiver can consume it.
 */
export function validateMessage(
  registry: Map<string, AgentMessageContract>,
  sender: string,
  receiver: string,
  messageType: MessageType,
): MessageValidation {
  const sendCheck = validateSend(registry, sender, messageType);
  if (!sendCheck.valid) return sendCheck;

  const recvCheck = validateReceive(registry, receiver, messageType);
  if (!recvCheck.valid) return recvCheck;

  return { valid: true };
}

// ── Code generation ──────────────────────────────────────────────

/**
 * Generate TypeScript type definitions from a contract registry.
 * Produces enum-like types per agent: DevMessageTypes, CriticMessageTypes, etc.
 */
export function generateTypeScript(registry: Map<string, AgentMessageContract>): string {
  const lines: string[] = [
    "// Auto-generated by workflow-message-types.ts (ELLIE-833)",
    "// Do not edit manually — regenerate from archetype definitions.",
    "",
    `export const MESSAGE_TYPES = ${JSON.stringify(MESSAGE_TYPES)} as const;`,
    `export type MessageType = typeof MESSAGE_TYPES[number];`,
    "",
  ];

  for (const [name, contract] of registry) {
    const pascalName = name.charAt(0).toUpperCase() + name.slice(1);
    lines.push(`/** Message types for ${name} agent (${contract.species} archetype) */`);
    lines.push(`export const ${pascalName}Produces = ${JSON.stringify(contract.produces)} as const;`);
    lines.push(`export const ${pascalName}Consumes = ${JSON.stringify(contract.consumes)} as const;`);
    lines.push(`export type ${pascalName}ProducesType = typeof ${pascalName}Produces[number];`);
    lines.push(`export type ${pascalName}ConsumesType = typeof ${pascalName}Consumes[number];`);
    lines.push("");
  }

  lines.push("/** Contract registry — agent name → produces/consumes */");
  lines.push("export const AGENT_CONTRACTS: Record<string, { produces: readonly MessageType[]; consumes: readonly MessageType[] }> = {");
  for (const [name, contract] of registry) {
    lines.push(`  ${name}: { produces: ${JSON.stringify(contract.produces)}, consumes: ${JSON.stringify(contract.consumes)} },`);
  }
  lines.push("};");

  return lines.join("\n");
}
